### ISSUE TITLE
No parser for 'jsonc' language

### ISSUE THREAD

**Issue by calebdw** [jamestthompson3/nvim-remote-containers#12]
Maybe I'm doing something wrong, but when I try to execute commands I get the following error:

```
E5108: Error executing lua ...local/share/nvim/runtime/lua/vim/treesitter/language.lua:25: no parser for 'jsonc' language, see :help treesitter-parsers
stack traceback:
        [C]: in function 'error'
        ...local/share/nvim/runtime/lua/vim/treesitter/language.lua:25: in function 'require_language'
        /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:112: in function 'get_string_parser'
        ...e/pack/packer/start/nvim-remote-containers/lua/utils.lua:6: in function 'jsonc_no_comment'
        ...e/pack/packer/start/nvim-remote-containers/lua/utils.lua:33: in function 'jsonc_to_json'
        ...e/pack/packer/start/nvim-remote-containers/lua/utils.lua:54: in function 'parseConfig'
        ...cker/start/nvim-remote-containers/lua/docker-compose.lua:15: in function 'composeDown'
        [string ":lua"]:1: in main chunk
```

I looked and there's not a 'jsonc' server available through 'nvim-lsp-installer'. Any help would be greatly appreciated.

Thanks!

**Comment by jamestthompson3** [comment]
Thanks for trying out the plugin!

You will need to install the JSONC (noted as [json with comments](https://github.com/nvim-treesitter/nvim-treesitter#supported-languages) in the treesitter repo) via **treesitter** and not nvim-lsp-installer. Given you have `nvim-treesitter` installed, the command to add jsonc support is `TSInstall jsonc`
