### ISSUE TITLE
How do you create a `devcontainer.json` file?

### ISSUE THREAD

**Issue by roblevy** [jamestthompson3/nvim-remote-containers#14]
Is there any help anywhere with creating a `devcontainer.json` file?

I started following [this](https://code.visualstudio.com/docs/remote/devcontainerjson-reference) but it's a bit hectic. I was just trying to connect to a running service in Docker compose.

Or do you normally set everything up in VSCode and get it to create the JSON for you?

**Comment by jamestthompson3** [comment]
I normally create them by hand. My setups aren't usually too complex so it's a pretty quick task. They usually look something like this:

```json
{
  "dockerFile": "Dockerfile",
  "forwardPorts": [3000],
  "workspaceMount": "${localWorkspaceFolder}",
  "workspaceFolder": "/workspace"
}
```

**Comment by roblevy** [comment]
Thanks for such a swift reply! Have you managed to make it work with Docker Compose? If so, do you have to specify all the Docker image stuff too, or can you just use the Docker Compose parts of the JSON spec?

**Comment by jamestthompson3** [comment]
It should work with docker-compose, so long as you have a docker-compose configuration file in your project.
