### ISSUE TITLE
Unable to attach to container

### ISSUE THREAD

**Issue by marvindore** [jamestthompson3/nvim-remote-containers#4]
Hello,
Thank you for creating this plugin, since downloading I haven't been able to get it to work. I installed it using Packer.nvim and run the following command `:AttachContainer`. A list of containers pops up, so I select a number then nothing happens. If I check my hostname using `vim.loop.os_gethostname` it shows I am still connected to the same host. Not sure how could I debug this as I am new to Lua.

**Comment by jamestthompson3** [comment]
Thanks for using the plugin! I can add some better logging and make sure `vim.g.currentContainer` is being properly set. The best way to see whether or not the container is running is to use `docker ps` and see if the container you chose is listed there.

**Comment by jamestthompson3** [comment]
https://github.com/jamestthompson3/nvim-remote-containers/commit/5ceb7440071180cca16e5820fb76a8ccf38b80f5 Should print things out better when starting and attaching to containers. Let me know if you still encounter issues.

**Comment by marvindore** [comment]
Thanks so much for the reply, the plugin will be extremely useful because I use the docker feature on VScode daily. I pulled your latest code changes and have taken the following steps:
- Start my container
- ran `docker ps` confirming container is running
- Opened neovim
- Executed :AttachContainer
- Selected my running container
- Then ran command `:Lua print(vim.g.currentContainer`
And the result was `nil`. I'm pretty sure I'm doing something wrong as I'm new to neovim, so I will keep looking around to see if I find anything.

**Comment by jamestthompson3** [comment]
I see the issue now. The flow for this plugin is based on _starting_ the container from inside nvim, but it currently doesn't do anything if the container has been started externally. [Here are the lines](https://github.com/jamestthompson3/nvim-remote-containers/blob/5ceb7440071180cca16e5820fb76a8ccf38b80f5/lua/docker.lua#L196-L205) that deal with this. My flow when creating this was just to have any easy way to start a container with the current working directory mounted inside. However, I can see the value of attaching to a container that's already running. What would be the assumptions and flow for this use case? If the working directory you are opening neovim in is mounted in the container, then it should "just work<sup>TM</sup>". But if you're wanting to edit other files inside the container (say some configuration file that's not in your working directory), then I'll need to make some changes.

**Comment by marvindore** [comment]
Ah I see! So currently I am running a laravel application in docker using the `sail` utility to start the containers. I'm guessing the flow of this use case would be for applications that are using docker compose spinning up multiple containers like web server, a database, etc. What is your current recommendation for using this plugin with docker-compose?

**Comment by jamestthompson3** [comment]
Currently, docker-compose support is in the todo list: https://github.com/jamestthompson3/nvim-remote-containers/projects/1#card-33550118. It could be a good first contribution!

**Comment by marvindore** [comment]
Awesome, I will give that a shot. I am still learning Lua so not sure how long it would take me but would love to contribute :-)

**Comment by jamestthompson3** [comment]
cool! I'm happy to help if you get stuck!
