### ISSUE TITLE
[Question] Neovim cannot run inside the container.

### ISSUE THREAD

**Issue by nabezokodaikon** [jamestthompson3/nvim-remote-containers#5]
# Problems summary
Neovim cannot run inside the container.

## Expected
neovim can run inside a container.

## Environment Information
* nvim-remote-containers version: 5ceb7440071180cca16e5820fb76a8ccf38b80f5
* OS: Mac
* neovim version: v0.6.0-dev+129-gadebbebdd

It may be my lack of understanding, but if you access the container created with `nvim-remote-containers` like` docker exec -it 398bf33fb329 /bin/bash`, you can use the `nvim` command. I am thinking.

**Comment by jamestthompson3** [comment]
Thanks for using the plugin, and thanks for all the info in the issue!

This plugin doesn't install `nvim` in the containers it creates. It reads the configuration from the `devcontainer.json` file found in your project directory (it assumes it's in the same working directory as the running neovim instance) and creates a container according to the configuration. Then, it will mount either the current working directory, or the directory listed as `localWorkspaceFolder` in the config as a volume in the container. This allows you to edit files in the directory in neovim on your filesystem and those changes are reflected inside the container.

**Comment by nabezokodaikon** [comment]
Thank you for your polite reply!
I found that the container doesn't need neovim.
So what's the difference between mounting a volume normally and using this plugin?

**Comment by jamestthompson3** [comment]
No difference, really. You just get to stay inside your editor :) it's useful if you want to automatically start up a specific container when you open a project (you can use a local nvim configuration in the project directory to add an autocmd for this), or if you want to build and run containers from inside of neovim.

**Comment by nabezokodaikon** [comment]
So that's it. understood.
thank you.
