### ISSUE TITLE
attempt to index upvalue 'fn' (a nil value)

### ISSUE THREAD

**Issue by vedsmand** [jamestthompson3/nvim-remote-containers#6]
### Problems summary
all available Vim commands are failing 

### Expected
all available Vim commands should work

### Environment Information
nvim-remote-containers version: 5ceb744
OS: Pop!_OS 21.04
neovim version: v0.4.4

### issue
hi, 
thank you for creating this plugin, it looks very promising.
I have the following issue however:
after installing i get the following errors on the commands  

**BuildImage**
E5105: Error while calling lua chunk: ../nvim-remote-containers/lua/docker.lua:8: attempt to index upvalue 'fn' (a nil value)

**AttachToContainer**
E5105: Error while calling lua chunk: ../nvim-remote-containers/lua/docker.lua:181: attempt to index upvalue 'fn' (a nil value)

**StartImage**
E5105: Error while calling lua chunk: ../nvim-remote-containers/lua/docker.lua:132: attempt to index upvalue 'fn' (a nil value)

all three commands error on calls related to vim.fn
https://github.com/jamestthompson3/nvim-remote-containers/blob/5ceb7440071180cca16e5820fb76a8ccf38b80f5/lua/docker.lua#L3

is this a module i need to install in order to get this to work or something ?

**Comment by vedsmand** [comment]
after playing around with this I found that this was a nvim version issue
after updating to nvim v 0.6.0 the vim.fn issue got resolved

now I have an issue in both BuildImage and AttachToContainer commands,
where the module fails on nil value for localworkspace folder

is it possible to share an example .devcontainer folder with a known working Dockerfile and devcontainer.json file ?
then it will be much easier for me to troubleshoot on my own 

thanks

**Comment by jamestthompson3** [comment]
Thanks for the detailed issue! As you discovered, this plugin only works with neovim 0.5.0+. Below are the Dockerfile and devcontainer.json files I use to test the plugin's functionality.


Dockerfile:

```dockerfile
FROM node:latest

WORKDIR /workspace
RUN ls
```

devcontainer.json

```json
{
  "dockerFile": "Dockerfile",
  "forwardPorts": [3000],
  "workspaceMount": "${localWorkspaceFolder}",
  "workspaceFolder": "/workspace"
}
```

**Comment by vedsmand** [comment]
perfect thanks,
got it up and running with your files provided

I might open up a pr to add the above files and some extra text to the README.md so non-nvim-devcontainer-ninjas can get this up and running with ease :)

thanks again

**Comment by jamestthompson3** [comment]
No problem! Thanks for your interest in the project! PRs are always welcome :)
